### ISSUE TITLE
Error contacting your node. Your platform may not be supported: win32 x64 v10.11.0

### ISSUE THREAD

**Issue by tw0r** [bitgrin/kingfish#8] opened 2019-03-13 08:15 UTC
Im getting this Error when creating wallet. 
OS: Win10 Pro 64bit, updated.

**Comment by tw0r** [comment] 2019-03-13 08:16
![image](https://user-images.githubusercontent.com/20809599/54263252-b2cddb80-4570-11e9-8e1c-9d12cd6066e5.png)

**Comment by pharazen** [comment] 2019-03-13 16:49
If you see "error contracting node" error, try this and report back if it worked:
1) Click the AUTHENTICATE tab
2) Enter your password

If this fails, try this:

1) Close Kingfish
2) Visit your home directory, ~ on Mac, C:/Users/username on windows
3) Open home/.bitgrin/main/bitgrin-server.toml
4) Change run_tui to = false
5) If you do not have any funds on your computer already, delete home/.bitgrin/main/wallet_data folder
6) Run kingfish again and let us know if it worked

Please report back how it went

**Comment by tw0r** [comment] 2019-03-13 18:08
First option didnt worked.
Second option worked.

**Comment by pharazen** [comment] 2019-03-13 22:07
Ok so confirmed, this is because of the TUI running. There is a permanent fix in v1.0.1, closing this.

**Closed** 2019-03-13 22:10 UTC
